@startuml
participant ": Server" as sv
participant ": ConnectionHandler" as ch
participant ": RequestHandler" as rh
participant ": EntityManagerSQL" as emSQL
participant "user : Account" as acc
participant "group : Usergroup" as grp

  activate sv

  [-> sv : connection client

  sv -> ch : <<create>>
  activate ch

  [-> ch : request

  ch -> rh : RequestHandler(request) <<create>>
  activate rh

  rh --> ch
  deactivate rh

  ch -> rh : run()
  activate rh

  rh -> acc: getAllGroups()
  activate acc

  acc -> emSQL: executeSQLStatement(sqlsatement)
  activate emSQL

  emSQL --> acc : ResultSet rs
  deactivate emSQL

  acc --> rh: Map<int, Usergroup> groups
  deactivate acc

  rh -> grp: getAllEvents()
  activate grp

  grp -> emSQL: executeSQLStatement(sqlsatement)
  activate emSQL

  emSQL --> grp : ResultSet rs
  deactivate emSQL

  grp --> rh: List<Event> events
  deactivate grp

  rh --> ch : event
  destroy rh

  [<-- ch : event
  deactivate ch

@enduml
