@startuml
participant ": Server" as sv
participant ": ConnectionHandler" as ch
participant ": RequestHandler" as rh
participant ": EntityManagerSQL" as emSQL
participant "user : Account" as acc

  activate sv

  [-> sv : connection client

  sv -> ch : <<create>>
  activate ch

  [-> ch : request

  ch -> rh : RequestHandler(request) <<create>>
  activate rh

  rh --> ch
  deactivate rh

  ch -> rh : run()
  activate rh

  rh -> acc: getAllGroups()
  activate acc

  acc -> emSQL: executeSQLStatement(sqlsatement)
  activate emSQL

  emSQL --> acc : ResultSet rs
  deactivate emSQL

  acc --> rh: Map<int, Usergroup> groups
  deactivate acc

  rh --> ch : group
  destroy rh

  [<-- ch : group
  deactivate ch

@enduml
