@startuml

participant ": FriendListViewHolder" as FLVH
participant "binding : FriendItemBinding" as FIB
participant "listener : FriendListFragment" as FCL
participant "FriendDetailActivity" as FDA
participant "view : View" as View


-> FLVH: <<create>>(binding:FriendItemBinding, listener:FriendListFragment)
activate FLVH

FLVH -> FIB: getRoot()
activate FIB
FIB --> FLVH: view:View
deactivate FIB

FLVH -> View : setOnClickListener(this)
activate View
View --> FLVH
deactivate View
<-- FLVH
deactivate FLVH

View <- : User clicks View
activate View
View ->> FLVH: onClick()
activate FLVH

FLVH -> FCL:onItemClicked(position:int, user:User)
activate FCL
FCL ->> FDA:start(user)
activate FDA
deactivate FDA
FCL --> FLVH
deactivate FCL
FLVH --> View
deactivate FLVH
@enduml