@startuml

package View <<Rectangle>> {
class FriendListFragment
class MapFragment
class EventListFragment
}
package ViewModel <<Rectangle>> {
    class FriendListViewModel
    class MapViewModel
    class EventListViewModel
}
package repository {
    class UserRepository
    class EventRepository
}
FriendListViewModel <-down- FriendListFragment
MapViewModel <-down- MapFragment
EventListViewModel <-down- EventListFragment
UserRepository <-down- FriendListViewModel
UserRepository <-down- MapViewModel
EventRepository <-down- MapViewModel
EventRepository <-down- EventListViewModel

package database {
    class UserDao
    class EventDao
    class treffDataBase
}

treffDataBase <-down- UserDao
treffDataBase <-down- EventDao

package networking {
    enum Error
    class RequestEncoder
    class ConnectionHandler
}


package Server <<Cloud>> {

}


UserDao <-right- UserRepository
RequestEncoder <-down- UserRepository
EventDao <-down- EventRepository
RequestEncoder <-left- EventRepository
ConnectionHandler <-down- RequestEncoder
Error <-right- RequestEncoder
Server <-down- ConnectionHandler

package SQL <<Database>> {
}

SQL <-down- treffDataBase

@enduml